services:
  postgres:
    image: postgres:16
    container_name: de_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-de_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-de_password}
      POSTGRES_DB: ${POSTGRES_DB:-de_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro

volumes:
  pgdata:
